repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests before commit
        entry: pytest script/tests/
        pass_filenames: false
        language: system
        stages: [commit]
