name: Run tests

on:
  push:
    branches: [main]  # または master
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: pytest script/tests/
  deploy:
    needs: test 
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      - name: Wait for Render app to be healthy
        run: |
          for i in {1..25}; do
            echo "Checking... attempt $i"
            status=$(curl -s -o /dev/null -w "%{http_code}" "https://nim-kp9h.onrender.com/healthcheck")
            if [ "$status" == "200" ]; then
              echo "App is up!"
              exit 0
            fi
            sleep 5
          done
          echo "Timed out waiting for app"
          exit 1

